networks:
  elk_network:
    ipam:
      config:
        - subnet: ${SUBNET_RANGE}
    name: elk_network
    driver: ${NETWORK_DRIVER}

volumes:
  elasticsearch_data:
    name: elasticsearch_data
    driver: ${VOLUME_DRIVER}
  kibana_data:
    name: kibana_data
    driver: ${VOLUME_DRIVER}

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:${STACK_VERSION}
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk_network
    ports:
      - ${ES_PORT}:${ES_PORT}
    environment:
      - node.name=elasticsearch
      - cluster.name=elk-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD-SHELL","curl -f -X GET http://localhost:${ES_PORT}/_cat/health"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 10s
      retries: 10

  kibana:
    container_name: kibana
    image: kibana:${STACK_VERSION}
    volumes:
      - kibana_data:/usr/share/kibana/data
    networks:
      - elk_network
    ports:
      - ${KIB_PORT}:${KIB_PORT}
    depends_on:
      elasticsearch:
        condition: service_healthy
